apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-python-app
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: create-python-app
        image: valentinebuki/my-python-app:0.2
        ports:
        - containerPort: 5000