apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-react-app
  labels:
    app: react
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: create-react-app
        image: staceypink/react-app
        ports:
        - containerPort: 80
